language: node_js
node_js:
  - "8"

sudo: false

before_install:
  - rvm install 2.6.2
  - rvm use 2.6.2
  - gem install hiptest-publisher
  - "hiptest-publisher -c cucumber-typescript.conf --without=actionwords --test-run-id=258520"
  - npm install

script:
  - npm run ci > report.json

after_script:
  - hiptest-publisher -c cucumber-typescript.conf --push=results.json --test-run-id=258520


